/**
 * Localized labels for the admin System Health slice.
 * Kept separate from components so both UI and tests can import them cheaply.
 */
export const healthLabels = {
  bn: {
    systemHealth: 'সিস্টেম হেলথ',
    database: 'ডেটাবেজ',
    connected: 'সংযুক্ত',
    disconnected: 'বিচ্ছিন্ন',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    noActivity: 'কোনো কার্যকলাপ নেই',
    deviceStatus: 'ডিভাইস স্ট্যাটাস',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    lastSeen: 'শেষ দেখা',
    sensorLogs: 'সেন্সর লগ (আজ)',
    automationRuns: 'অটোমেশন রান',
    powerOutages: 'বিদ্যুৎ বিভ্রাট',
    errorLogs: 'এরর লগ',
    noErrors: 'কোনো এরর নেই',
    systemOk: 'সিস্টেম স্বাভাবিক',
    allUsers: 'সকল ইউজার',
    selectUser: 'ইউজার নির্বাচন করুন',
    searchPlaceholder: 'নাম বা ফোন দিয়ে খুঁজুন...',
    noUserFound: 'কোনো ইউজার পাওয়া যায়নি',
    userHealth: 'ইউজার হেলথ',
    noDeviceData: 'কোনো ডিভাইস ডেটা নেই',
    mode: 'মোড',
    battery: 'ব্যাটারি',
    signal: 'সিগন্যাল',
    uptime: 'আপটাইম',
    lastSync: 'শেষ সিঙ্ক',
    firmware: 'ফার্মওয়্যার',
    alertsToday: 'আজকের অ্যালার্ট',
    sensorHealth: 'সেন্সর হেলথ',
    temperature: 'তাপমাত্রা',
    humidity: 'আর্দ্রতা',
    ammonia: 'অ্যামোনিয়া',
    waterFlow: 'পানি প্রবাহ',
    working: 'সচল',
    notWorking: 'অচল',
    noData: 'ডেটা নেই',
    lastReading: 'শেষ রিডিং',
    outOfRange: 'অস্বাভাবিক',
    normal: 'স্বাভাবিক',
    attentionRequired: 'মনোযোগ প্রয়োজন',
    problemUsers: 'সমস্যাযুক্ত ইউজার',
    noProblem: 'সকল সিস্টেম স্বাভাবিক',
    deviceOffline: 'ডিভাইস অফলাইন',
    noSensorData: 'সেন্সর ডেটা নেই',
    powerOutage: 'বিদ্যুৎ বিভ্রাট',
    criticalAlert: 'জরুরি অ্যালার্ট',
    viewDetails: 'বিস্তারিত দেখুন',
  },
  en: {
    systemHealth: 'System Health',
    database: 'Database',
    connected: 'Connected',
    disconnected: 'Disconnected',
    recentActivity: 'Recent Activity',
    noActivity: 'No activity',
    deviceStatus: 'Device Status',
    online: 'Online',
    offline: 'Offline',
    lastSeen: 'Last seen',
    sensorLogs: 'Sensor Logs (Today)',
    automationRuns: 'Automation Runs',
    powerOutages: 'Power Outages',
    errorLogs: 'Error Logs',
    noErrors: 'No errors',
    systemOk: 'System OK',
    allUsers: 'All Users',
    selectUser: 'Select User',
    searchPlaceholder: 'Search by name or phone...',
    noUserFound: 'No user found',
    userHealth: 'User Health',
    noDeviceData: 'No device data',
    mode: 'Mode',
    battery: 'Battery',
    signal: 'Signal',
    uptime: 'Uptime',
    lastSync: 'Last Sync',
    firmware: 'Firmware',
    alertsToday: 'Alerts Today',
    sensorHealth: 'Sensor Health',
    temperature: 'Temperature',
    humidity: 'Humidity',
    ammonia: 'Ammonia',
    waterFlow: 'Water Flow',
    working: 'Working',
    notWorking: 'Not Working',
    noData: 'No Data',
    lastReading: 'Last Reading',
    outOfRange: 'Out of Range',
    normal: 'Normal',
    attentionRequired: 'Attention Required',
    problemUsers: 'Problem Users',
    noProblem: 'All Systems Normal',
    deviceOffline: 'Device Offline',
    noSensorData: 'No Sensor Data',
    powerOutage: 'Power Outage',
    criticalAlert: 'Critical Alert',
    viewDetails: 'View Details',
  },
} as const;

export type HealthLanguage = keyof typeof healthLabels;
export type HealthLabels = (typeof healthLabels)['bn'];
